### PR TITLE
Bump to version 0.2.1

### PR DESCRIPTION
**Pull request by dynamiccast**
The PR sets the required stuff to bump version number

### CODE REVIEW

**Comment by dynamiccast** [comment]
This PR is not to be accepted before master is tested

**Comment by domrod** [comment]
Could you also correct a small typo in README file?
usefull -> useful

**Comment by dynamiccast** [comment]
This is to be part of an other PR. Mind to take care of it ?

**Comment by domrod** [comment]
No pb. I'll take that in charge for the next PR.

**Pull request merged**
